name: 'tyntec SMS'
description: 'Block the given number of milliseconds'
author: 'tyntec GmbH'
inputs:
  milliseconds:
    required: true
    description: 'The number of milliseconds to block'
    default: '500'
outputs:
  time:
    description: 'The time the action stopped'
runs:
  using: 'node12'
  main: 'dist/index.js'
